# Generated by Django 4.2 on 2025-10-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
